spring.application.name=tea-stall-management-system-backend

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/postDB?ssl=false
spring.datasource.username=postgres
spring.datasource.password=Shaik@123
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
